/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.4
 * Generated at: 2018-02-21 13:09:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.jasig.cas.CasVersion;

public final class errors_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/home/mils/Downloads/apache-tomcat-9.0.4/webapps/cas/WEB-INF/lib/spring-2.0.3.jar!/META-INF/spring.tld", Long.valueOf(1161339368000L));
    _jspx_dependants.put("jar:file:/home/mils/Downloads/apache-tomcat-9.0.4/webapps/cas/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-2.0.3.jar", Long.valueOf(1176458094000L));
    _jspx_dependants.put("/WEB-INF/view/jsp/default/ui/includes/bottom.jsp", Long.valueOf(1170340748000L));
    _jspx_dependants.put("jar:file:/home/mils/Downloads/apache-tomcat-9.0.4/webapps/cas/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/WEB-INF/view/jsp/default/ui/includes/top.jsp", Long.valueOf(1170340748000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1176458094000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.jasig.cas.CasVersion");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>JA-SIG Central Authentication Service (CAS)</title>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\"\tcontent=\"application/xhtml+xml; charset=UTF-8\" />\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"Central Authentication Service,JA-SIG,CAS\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/home.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/jasig.css\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\t\t<script src=\"js/common.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body onload=\"init();\">\r\n");
      out.write("\t\t<div id=\"jasig-banner\">\r\n");
      out.write("\t\t\t<div id=\"jasig-logo\"><a href=\"http://www.ja-sig.org\"><img src=\"images/jasig-logo.gif\" width=\"71\" height=\"19\" alt=\"JA-SIG logo\" /></a></div>\r\n");
      out.write("\t\t\t<form action=\"http://www.google.com/u/jasig\" method=\"get\" style=\"display:inline;margin:0;padding:0;\">\r\n");
      out.write("\t\t\t<ul id=\"jasig-nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"http://www.ja-sig.org/products/\">Products</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://www.ja-sig.org/conferences.html\">Conferences</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://clearinghouse.ja-sig.org/\">Clearinghouse</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://www.ja-sig.org/facebook/\">Community</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"http://developer.ja-sig.org\">Developers</a></li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<input value=\"ja-sig.org\" name=\"domains\" type=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t<input value=\"ja-sig.org\" name=\"sitesearch\" type=\"hidden\" />\r\n");
      out.write("\t\t\t\t\t<input style=\"font-size: 11px;\" maxlength=\"255\" name=\"q\" type=\"text\" />\r\n");
      out.write("\t\t\t\t\t<input name=\"sa\" type=\"image\" src=\"./images/input-search.gif\" value=\"search\" style=\"vertical-align: top;\" />\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"header\">\r\n");
      out.write("\t\t\t<img src=\"./images/banner.png\" width=\"687\" height=\"76\" alt=\"Central Authentication Service\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"content\">");
      out.write("\n");
      out.write("\t\t<div id=\"welcome\">\n");
      out.write("\t\t\t<h2>CAS is Unavailable</h2>\n");
      out.write("\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t   A general exception occurred while trying to access CAS.  Please notify your system administrator.\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"copyright\">\r\n");
      out.write("\t\t\t\t<p>Copyright &copy; 2005-2006 JA-SIG. All rights reserved.</p>\r\n");
      out.write("\t\t\t\t<p><a href=\"http://www.ja-sig.org/products/cas/\">Home Page</a> | <a href=\"http://www.ja-sig.org/wiki/display/CAS/Home\">Wiki</a> | <a href=\"http://www.ja-sig.org/issues\">Issue Tracker</a> | <a href=\"http://www.ja-sig.org/products/cas/community/lists/index.html\">Mailing Lists</a></p>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<p>Powered by <a href=\"http://www.ja-sig.org/products/cas/\">JA-SIG CAS ");
      out.print(CasVersion.getVersion() );
      out.write("</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div><!-- END CONTENT -->\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
